### ISSUE TITLE
[FATAL tini (7)] exec /run.sh failed: Permission denied

### ISSUE THREAD

**Issue by sbou88** [sjthespian/addon-tuyagateway#6]
Hello, I just install this addon to home assistant on synology nas, but i get this error 

[FATAL tini (7)] exec /run.sh failed: Permission denied

I don't understand why and how to correct that.

**Comment by sjthespian** [comment]
That implies that for some reason the git clone that runs in the docker build didn't keep the correct permissions on the file. I can add that to the Dockerfile.

**Comment by sjthespian** [comment]
Fixed in 0.5 release.
